-- cPanel mysql backup
GRANT USAGE ON *.* TO 'thejsj'@'localhost' IDENTIFIED BY PASSWORD '*37B4F8E5B3802CF19C94D9923BAF8748D3B9E3D9';
GRANT ALL PRIVILEGES ON `thejsj\_veco`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_baseball`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_inter`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_servermon`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_ern`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_ilc`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_fb`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_moma`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_newportfolio`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_xyz`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_wp475`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_famtabl`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_nosotrus`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_canada`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_opc`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_speeches`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_adelle`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_wp610`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_wpbrdm`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_yamla`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_movieGenerator`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_gregarius`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_jsj3`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_jsj5`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_processing`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_moad`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_nways`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_nposrts`.* TO 'thejsj'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_%`.* TO 'thejsj'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_adelle'@'localhost' IDENTIFIED BY PASSWORD '*2D1C65C3DF3EA7A2F89118F94BDCA4AF847B4E06';
GRANT ALL PRIVILEGES ON `thejsj\_adelle`.* TO 'thejsj_adelle'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_ern'@'localhost' IDENTIFIED BY PASSWORD '*4495A83041CB924BD7CDDCDCEC2F384D10853E78';
GRANT ALL PRIVILEGES ON `thejsj\_ern`.* TO 'thejsj_ern'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_famtabl'@'localhost' IDENTIFIED BY PASSWORD '*3284515EA99E543DAA14B93329B4547F801FA81E';
GRANT ALL PRIVILEGES ON `thejsj\_famtabl`.* TO 'thejsj_famtabl'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_high'@'localhost' IDENTIFIED BY PASSWORD '*E9457BFECF9E743DF97CA14A8A8B2A9545B91B5A';
GRANT ALL PRIVILEGES ON `thejsj\_servermon`.* TO 'thejsj_high'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_moad`.* TO 'thejsj_high'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_low'@'localhost' IDENTIFIED BY PASSWORD '*B9C4E7E78B3160DA32B4E90859F32857909BE12D';
GRANT ALL PRIVILEGES ON `thejsj\_gregarius`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_ilc`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_canada`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_processing`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_jsj5`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_speeches`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_jsj3`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_movieGenerator`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_moma`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_veco`.* TO 'thejsj_low'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_baseball`.* TO 'thejsj_low'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_mid'@'localhost' IDENTIFIED BY PASSWORD '*1744570334519BE6D53BE491C76688B39042E0B2';
GRANT ALL PRIVILEGES ON `thejsj\_nosotrus`.* TO 'thejsj_mid'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_fb`.* TO 'thejsj_mid'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_inter`.* TO 'thejsj_mid'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_nways`.* TO 'thejsj_mid'@'localhost';
GRANT ALL PRIVILEGES ON `thejsj\_xyz`.* TO 'thejsj_mid'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_nposrts'@'localhost' IDENTIFIED BY PASSWORD '*1389BF1D48BC7E65826AF1C0EBA402E55CF00D30';
GRANT ALL PRIVILEGES ON `thejsj\_nposrts`.* TO 'thejsj_nposrts'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_opc'@'localhost' IDENTIFIED BY PASSWORD '*4A43B06D01965A95D0F7A5606DAE38E143E3965F';
GRANT ALL PRIVILEGES ON `thejsj\_opc`.* TO 'thejsj_opc'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_top'@'localhost' IDENTIFIED BY PASSWORD '*830826E634411D11877309E745759933DF54420C';
GRANT ALL PRIVILEGES ON `thejsj\_newportfolio`.* TO 'thejsj_top'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_wp475'@'localhost' IDENTIFIED BY PASSWORD '*BD174A694C5E5B028FB445797005FC4CBDD446DC';
GRANT ALL PRIVILEGES ON `thejsj\_wp475`.* TO 'thejsj_wp475'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_wp610'@'localhost' IDENTIFIED BY PASSWORD '*BE5AE347CF84308E1D977E24EEC6D08392DA9A6E';
GRANT ALL PRIVILEGES ON `thejsj\_wp610`.* TO 'thejsj_wp610'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_wpbrdm'@'localhost' IDENTIFIED BY PASSWORD '*12398BB78F573BC10596EF4DEB88D401A8F927DC';
GRANT ALL PRIVILEGES ON `thejsj\_wpbrdm`.* TO 'thejsj_wpbrdm'@'localhost';
GRANT USAGE ON *.* TO 'thejsj_yamla'@'localhost' IDENTIFIED BY PASSWORD '*6979D0F9FA934542AB9BF6027E7E95D325D56914';
GRANT ALL PRIVILEGES ON `thejsj\_yamla`.* TO 'thejsj_yamla'@'localhost';
